version: '3'
services:
  flask:
    build:
      context: .
    container_name: flask
    restart: unless-stopped
    depends_on:

      - broker_redis
    networks:
      - backend
      - reverse-proxy

  broker_redis:
    image: "redis"
    container_name: redis
    restart: unless-stopped
    networks:
      - backend

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - reverse-proxy
    depends_on:
      - flask


networks:
  backend:
    driver: bridge
  reverse-proxy:
    driver: bridge
